###REQUISIÇÂO GET

GET http://localhost:5206/

###

GET http://localhost:5206/lojas

###
GET http://localhost:5206/lojas/0

###
GET http://localhost:5206/lojas/pedidos/1

###REQUISIÇÂO POST

POST http://localhost:5206/lojas/pedidos
Content-Type: application/json

{
    "Id":1,
    "Nome": "Adega Brasil",
    "Taxa": "R$ 10",
    "Nota": 8,
    "Entrega":false
}

###REQUISIÇÂO PUT

PUT  http://localhost:5206/pedidos/1

{
    "Nome": "Comprar verdes",
    "Concluida":false
}

###REQUISIÇÂO DELETE

DELETE http://localhost:5206/pedidos/123
