// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace delivri.Migrations
{
    [DbContext(typeof(BDD))]
    [Migration("20240414203102_Relacionamento")]
    partial class Relacionamento
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Cardapio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Item")
                        .HasColumnType("int");

                    b.Property<string>("ItemNome")
                        .HasColumnType("longtext");

                    b.Property<int?>("LojasId")
                        .HasColumnType("int");

                    b.Property<float>("Preco")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("LojasId");

                    b.ToTable("Cardapio");
                });

            modelBuilder.Entity("Lojas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Entrega")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<float>("Nota")
                        .HasColumnType("float");

                    b.Property<float>("Taxa")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Lojas");
                });

            modelBuilder.Entity("Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CardapioId")
                        .HasColumnType("int");

                    b.Property<string>("Detalhes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CardapioId");

                    b.ToTable("Pedido");
                });

            modelBuilder.Entity("Cardapio", b =>
                {
                    b.HasOne("Lojas", null)
                        .WithMany("Cardapios")
                        .HasForeignKey("LojasId");
                });

            modelBuilder.Entity("Pedido", b =>
                {
                    b.HasOne("Cardapio", null)
                        .WithMany("Pedidos")
                        .HasForeignKey("CardapioId");
                });

            modelBuilder.Entity("Cardapio", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("Lojas", b =>
                {
                    b.Navigation("Cardapios");
                });
#pragma warning restore 612, 618
        }
    }
}
