###REQUISIÇÂO GET

GET http://localhost:5206/

###

GET http://localhost:5206/lojas

###
GET http://localhost:5206/lojas/pedidos

###
GET http://localhost:5206/lojas/pedidos/1

###REQUISIÇÂO POST

POST http://localhost:5206/pedidos
Content-Type: application/json

{
    "Nome": "Adega Brasil",
    "Taxa": 10,
    "Nota": 8,
    "Entrega": true
}

###REQUISIÇÂO PUT

PUT  http://localhost:5206/pedidos/1
Content-Type: application/json

{
    "Nome": "Adega Brasil",
    "Taxa": 10,
    "Nota": 8,
    "Entrega":false
}

###REQUISIÇÂO DELETE

DELETE http://localhost:5206/pedidos/123
